### ISSUE TITLE
'Current language' field for translator object

### ISSUE THREAD

**Issue by Forevener** [Appsilon/shiny.i18n#44]
Could you make translation_language field of a translator object public again, please? Or make a corresponding function.

**Comment by dokato** [comment]
Good point @Forevener. In theory this is redundant, because by default you use "key translation", then you may change you language with `set_translation_language` method, so you know explicitly with what language code you're dealing with. But it doesn't harm to have getter for that.

This option is available with `get_translation_language`, check github installation.
